function [A,b] = Abrhs(Is,Iw,Mm,R,d,g,ms,mw,theta,thetadot)
%ABRHS
%    [A,B] = ABRHS(IS,IW,MM,R,D,G,MS,MW,THETA,THETADOT)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    28-Dec-2023 11:09:50

t2 = cos(theta);
t3 = sin(theta);
t4 = d.^2;
t5 = -Is;
t6 = ms.*t4;
t7 = R.*d.*ms.*t2;
t8 = -t6;
t9 = -t7;
A = reshape([t5+t8+t9,t5+t8,-Iw-R.^2.*mw-R.*ms.*(R+d.*t2),t9],[2,2]);
if nargout > 1
    b = [-d.*ms.*t3.*(g+R.*thetadot.^2);-Mm-d.*g.*ms.*t3];
end
